[project]
name = "analyze"
version = "0.1.0"
description = "Analyze benchmarks"
readme = "../README.md"
requires-python = ">=3.13"
dependencies = ["matplotlib>=3.10.8", "numpy>=2.4.1", "tabulate>=0.9.0"]
