[advisories]
version = 2
yanked = "warn"
ignore = [
    # `paste` is unmaintained - doesn't matter
    "RUSTSEC-2024-0436",
    # `bincode` is unmaintained - unused
    "RUSTSEC-2025-0141",
]

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"

[licenses]
version = 2
confidence-threshold = 0.8

allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Unlicense",
    "BSL-1.0",
    "0BSD",
    "MPL-2.0",
    "Zlib",
]

exceptions = [
    # CC0 is a permissive license but somewhat unclear status for source code
    # so we prefer to not have dependencies using it
    # https://tldrlegal.com/license/creative-commons-cc0-1.0-universal
    { allow = ["CC0-1.0"], name = "tiny-keccak" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    # Used only for testing.
    "https://github.com/oli-obk/ui_test",
    # Used only for benchmarks.
    "https://github.com/DaniPopes/codspeed-rust",
]
