[package]
name = "sulk"
description = "Solidity compiler"
homepage = "https://github.com/paradigmxyz/sulk/"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[build-dependencies]
vergen = { workspace = true, features = ["build", "git", "gitcl"] }

[dependencies]
sulk-config = { workspace = true, features = ["clap"] }
sulk-data-structures.workspace = true
sulk-interface = { workspace = true, features = ["json"] }
sulk-resolve.workspace = true

clap = { workspace = true, features = ["derive"] }
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["registry", "env-filter", "fmt"] }
# tracing.workspace = true

[dev-dependencies]
sulk-tester.workspace = true

[features]
nightly = [
    "sulk-config/nightly",
    "sulk-data-structures/nightly",
    "sulk-interface/nightly",
    "sulk-resolve/nightly",
    "sulk-tester/nightly",
]

[[test]]
name = "tests"
path = "./tests.rs"
harness = false
