[alias]
xtask = "run --package xtask --bin xtask --"
# Override `cargo auditable` to run PGO+BOLT build instead (hack for cargo-dist)
auditable = "xtask pgo-build --"
tq = "xtask test"
qt = "tq"
ryul = "run --package solar-compiler --bin solar -- --language yul -Zparse-yul"
bless = "uibless"
uitest = "xtask test ui"
uibless = "xtask test ui --bless"

# Required for `dist` to work with linux arm targets: https://github.com/axodotdev/cargo-dist/issues/74#issuecomment-2053680080
[env]
CC_aarch64_unknown_linux_musl = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

# Increase the stack size to 10MB for Windows targets, which is in line with Linux
# (whereas default for Windows is 1MB).
[target.x86_64-pc-windows-msvc]
rustflags = ["-Clink-arg=/STACK:10000000"]

[target.i686-pc-windows-msvc]
rustflags = ["-Clink-arg=/STACK:10000000"]
