[package]
name = "sulk-interface"
description = "Source positions, diagnostics, and related helper functions"
homepage = "https://github.com/danipopes/sulk/blob/main/crates/interface"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
sulk-data-structures.workspace = true
sulk-macros.workspace = true

bumpalo.workspace = true
match_cfg.workspace = true
md-5.workspace = true
scoped-tls.workspace = true
unicode-width.workspace = true

# diagnostics
anstream.workspace = true
anstyle.workspace = true
annotate-snippets.workspace = true

# json
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[features]
json = ["dep:serde", "dep:serde_json"]

nightly = ["sulk-data-structures/nightly", "sulk-macros/nightly"]
